import { TravelData } from '../components/TravelForm';
import { TravelerDetailsData } from '../components/TravelerDetails';
import { format } from 'date-fns';

export interface TripExportData {
  travelData: TravelData;
  travelerData: TravelerDetailsData;
  totalBudget: number;
  generatedAt: Date;
}

export const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(amount);
};

export const generateTripText = (data: TripExportData): string => {
  const { travelData, travelerData, totalBudget, generatedAt } = data;
  
  return `
🛫 VOYAGER - Kerala Trip Itinerary 🛫
Generated on: ${format(generatedAt, 'PPP')}

═══════════════════════════════════════

📍 TRIP OVERVIEW
═══════════════════════════════════════
🏠 From: ${travelData.source}
🎯 To: ${travelData.destination}, Kerala
📅 Duration: ${travelData.duration} days
🗓️ Start Date: ${travelData.startDate ? format(travelData.startDate, 'PPP') : 'Not set'}
🗓️ End Date: ${travelData.endDate ? format(travelData.endDate, 'PPP') : 'Not set'}
👥 Travelers: ${travelerData.travelers.length} people

═══════════════════════════════════════

👥 TRAVELER DETAILS
═══════════════════════════════════════
${travelerData.travelers.map((traveler, index) => `
${index + 1}. ${traveler.name}
   Age: ${traveler.age}
   Contact: ${traveler.contact}${index === 0 ? ' (Primary)' : ''}
`).join('')}

🏠 Accommodation: ${travelerData.accommodationType.replace('-', ' ').toUpperCase()}
🚗 Transport: ${travelerData.transportPreference.replace('-', ' ').toUpperCase()}

═══════════════════════════════════════

💰 BUDGET ESTIMATE
═══════════════════════════════════════
Total Estimated Cost: ${formatCurrency(totalBudget)}

This includes:
• Accommodation for ${travelData.duration} days
• Transportation costs
• Food and meals
• Sightseeing and attractions
• Shopping and miscellaneous expenses

═══════════════════════════════════════

🌟 KERALA HIGHLIGHTS TO EXPLORE
═══════════════════════════════════════
Based on your destination: ${travelData.destination}

Kerala offers:
🌴 Backwaters & Houseboats
🏔️ Hill Stations & Tea Gardens  
🏖️ Pristine Beaches
🎭 Rich Culture & Heritage
🍛 Authentic Kerala Cuisine
🌿 Ayurvedic Wellness

═══════════════════════════════════════

📱 IMPORTANT NOTES
═══════════════════════════════════════
• Budget estimates are approximate and may vary
• Book accommodations in advance for better rates
• Check weather conditions before travel
• Carry necessary documents and ID proofs
• Respect local culture and traditions

═══════════════════════════════════════

Generated by VOYAGER - Kerala Travel Planner
Your trusted companion for exploring Kerala! 🌴

Visit Kerala Tourism: www.keralatourism.org
Emergency: 112 | Tourist Helpline: 0471-2321132

═══════════════════════════════════════
`;
};

export const generateTripHTML = (data: TripExportData): string => {
  const { travelData, travelerData, totalBudget, generatedAt } = data;
  
  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kerala Trip Itinerary - ${travelData.destination}</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            color: #333; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 20px;
            background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%);
        }
        .header { 
            background: linear-gradient(135deg, #059669 0%, #0d9488 100%);
            color: white; 
            padding: 30px; 
            border-radius: 15px; 
            text-align: center; 
            margin-bottom: 30px;
            box-shadow: 0 10px 30px rgba(5, 150, 105, 0.3);
        }
        .header h1 { 
            margin: 0; 
            font-size: 2.5em; 
            font-weight: bold;
        }
        .header p { 
            margin: 10px 0 0 0; 
            opacity: 0.9;
        }
        .section { 
            background: white; 
            padding: 25px; 
            margin-bottom: 20px; 
            border-radius: 12px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
            border-left: 5px solid #059669;
        }
        .section h2 { 
            color: #059669; 
            margin-top: 0; 
            font-size: 1.5em;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .traveler { 
            background: #f8fafc; 
            padding: 15px; 
            margin: 10px 0; 
            border-radius: 8px;
            border-left: 3px solid #10b981;
        }
        .budget-highlight { 
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
            color: white; 
            padding: 20px; 
            border-radius: 10px; 
            text-align: center; 
            font-size: 1.3em; 
            font-weight: bold;
            margin: 20px 0;
        }
        .grid { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); 
            gap: 15px; 
            margin: 15px 0;
        }
        .grid-item { 
            background: #f1f5f9; 
            padding: 15px; 
            border-radius: 8px;
            text-align: center;
        }
        .grid-item strong { 
            color: #059669; 
            display: block; 
            margin-bottom: 5px;
        }
        .highlights { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); 
            gap: 10px;
        }
        .highlight-item { 
            background: linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%);
            padding: 15px; 
            border-radius: 8px; 
            text-align: center;
            border: 2px solid #a7f3d0;
        }
        .footer { 
            text-align: center; 
            margin-top: 30px; 
            padding: 20px;
            background: #1f2937; 
            color: white; 
            border-radius: 10px;
        }
        .footer a { color: #10b981; }
        @media print {
            body { background: white; }
            .section { box-shadow: none; border: 1px solid #e5e7eb; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🛫 VOYAGER</h1>
        <p>Kerala Trip Itinerary</p>
        <p>Generated on ${format(generatedAt, 'PPP')}</p>
    </div>
    
    <div class="section">
        <h2>📍 Trip Overview</h2>
        <div class="grid">
            <div class="grid-item">
                <strong>From</strong>
                ${travelData.source}
            </div>
            <div class="grid-item">
                <strong>To</strong>
                ${travelData.destination}
            </div>
            <div class="grid-item">
                <strong>Duration</strong>
                ${travelData.duration} days
            </div>
            <div class="grid-item">
                <strong>Travelers</strong>
                ${travelerData.travelers.length} people
            </div>
        </div>
        
        <div class="grid">
            <div class="grid-item">
                <strong>Start Date</strong>
                ${travelData.startDate ? format(travelData.startDate, 'PPP') : 'Not set'}
            </div>
            <div class="grid-item">
                <strong>End Date</strong>
                ${travelData.endDate ? format(travelData.endDate, 'PPP') : 'Not set'}
            </div>
        </div>
    </div>
    
    <div class="section">
        <h2>👥 Traveler Details</h2>
        ${travelerData.travelers.map((traveler, index) => `
        <div class="traveler">
            <strong>${traveler.name}${index === 0 ? ' (Primary)' : ''}</strong>
            <p>Age: ${traveler.age} | Contact: ${traveler.contact}</p>
        </div>
        `).join('')}
        
        <div class="grid" style="margin-top: 20px;">
            <div class="grid-item">
                <strong>Accommodation</strong>
                ${travelerData.accommodationType.replace('-', ' ').toUpperCase()}
            </div>
            <div class="grid-item">
                <strong>Transport</strong>
                ${travelerData.transportPreference.replace('-', ' ').toUpperCase()}
            </div>
        </div>
    </div>
    
    <div class="section">
        <h2>💰 Budget Estimate</h2>
        <div class="budget-highlight">
            Total Estimated Cost: ${formatCurrency(totalBudget)}
        </div>
        <p><strong>This estimate includes:</strong></p>
        <ul>
            <li>Accommodation for ${travelData.duration} days</li>
            <li>Transportation costs</li>
            <li>Food and meals</li>
            <li>Sightseeing and attractions</li>
            <li>Shopping and miscellaneous expenses</li>
        </ul>
    </div>
    
    <div class="section">
        <h2>🌟 Kerala Highlights</h2>
        <p><strong>Destination:</strong> ${travelData.destination}</p>
        <div class="highlights">
            <div class="highlight-item">🌴 Backwaters</div>
            <div class="highlight-item">🏔️ Hill Stations</div>
            <div class="highlight-item">🏖️ Beaches</div>
            <div class="highlight-item">🎭 Culture</div>
            <div class="highlight-item">🍛 Cuisine</div>
            <div class="highlight-item">🌿 Ayurveda</div>
        </div>
    </div>
    
    <div class="section">
        <h2>📱 Important Notes</h2>
        <ul>
            <li>Budget estimates are approximate and may vary based on season and preferences</li>
            <li>Book accommodations and transport in advance for better rates</li>
            <li>Check weather conditions before your travel dates</li>
            <li>Carry necessary documents and ID proofs</li>
            <li>Respect local culture and traditions</li>
        </ul>
    </div>
    
    <div class="footer">
        <p><strong>Generated by VOYAGER - Kerala Travel Planner</strong></p>
        <p>Your trusted companion for exploring God's Own Country! 🌴</p>
        <p>Visit Kerala Tourism: <a href="http://www.keralatourism.org">www.keralatourism.org</a></p>
        <p>Emergency: 112 | Tourist Helpline: 0471-2321132</p>
    </div>
</body>
</html>
  `;
};

export const downloadTripAsFile = (data: TripExportData, format: 'txt' | 'html' = 'txt') => {
  const content = format === 'html' ? generateTripHTML(data) : generateTripText(data);
  const fileName = `Kerala_Trip_${data.travelData.destination.replace(/[^a-zA-Z0-9]/g, '_')}_${format(data.generatedAt, 'yyyy-MM-dd')}.${format}`;
  const mimeType = format === 'html' ? 'text/html' : 'text/plain';
  
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const printTrip = (data: TripExportData) => {
  const htmlContent = generateTripHTML(data);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
};